version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:836057931165:task-definition/aws-hello-world:1"
        LoadBalancerInfo:
          ContainerName: "aws-rest-api"
          ContainerPort: "80"
        PlatformVersion: "LATEST"